<a href="https://colab.research.google.com/github/therajatonly579/DeeployCV-Assignment-4/blob/main/DeeployCVA4Q7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1


In [20]:
import tensorflow as tf
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
# Load the Iris dataset
data = tf.keras.utils.get_file(
    "iris.data",
    "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
)

# Define column names
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

# Load dataset into a DataFrame
iris = pd.read_csv(data, header=None, names=column_names)



# Display the first few rows
print(iris.head())


   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [21]:
from tensorflow.keras.utils import to_categorical
# Encode target labels as integers
iris['species'] = iris['species'].astype('category').cat.codes

In [22]:
# Separate features (X) and target (y)
X = iris.iloc[:, :-1].values  # All columns except the last
y = iris.iloc[:, -1].values   # Only the last column

In [23]:
# Print shapes and examples
print("Features (X):", X[:5])
print("Target (y):", y[:5])
print("X shape:", X.shape)
print("y shape:", y.shape)

Features (X): [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Target (y): [0 0 0 0 0]
X shape: (150, 4)
y shape: (150,)


In [24]:
from sklearn.preprocessing import StandardScaler
# Feature scaling (standardization)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
# One-hot encoding for target labels
y_encoded = to_categorical(y)

In [26]:
# split the dataset
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

Task 2


In [28]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
# Build the neural network
model = Sequential([
    Dense(8, activation='relu', input_shape=(4,)),  # Input layer + Hidden layer (8 neurons, ReLU)
    Dense(3, activation='softmax')                 # Output layer (3 neurons, Softmax)
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Task 3

In [35]:
# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=5, validation_split=0.2, verbose=1)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9499 - loss: 0.1130 - val_accuracy: 1.0000 - val_loss: 0.0643
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9531 - loss: 0.0811 - val_accuracy: 1.0000 - val_loss: 0.0644
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9815 - loss: 0.0703 - val_accuracy: 1.0000 - val_loss: 0.0638
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9701 - loss: 0.0547 - val_accuracy: 1.0000 - val_loss: 0.0660
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9442 - loss: 0.1016 - val_accuracy: 1.0000 - val_loss: 0.0656
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9846 - loss: 0.0520 - val_accuracy: 1.0000 - val_loss: 0.0636
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9769 - loss: 0.0739 - val_accuracy: 1.0000 - val_loss: 0.0627
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9643 - loss: 0.0809 - val_accuracy: 1.0000 - 

Task 4

In [36]:
# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9667 - loss: 0.0492
Test Loss: 0.0492, Test Accuracy: 0.9667


Task 3